ansible_user: ovp
ansible_password: Zxc123456
#ansible_user: vagrant
#ansible_password: vagrant
#ansible_port: 5985
#ansible_winrm_scheme: http
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
